version: "3.3"

services:
  database:
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"

  raw3:
    ports:
      - "4200:4200"
    environment:
      PORT: 4200
      MONGODB_USER: "root"
      MONGODB_PASSWORD: "root"
