version: "3.3"

services:
  database:
    container_name: database
    image: mongo
    restart: always
    expose:
      - 27017

  raw3:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: raw3
    image: raw3
    command: npm run serve:ssr
    restart: always
    depends_on:
      - database
    links:
      - database
    environment:
      MONGODB_URI: "database:27017/raw3"
