version: "3.3"

services:
  database:
    container_name: database
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"

  raw3:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: raw3
    image: raw3
    command: npm run serve:ssr
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    links:
      - database
    environment:
      VIRTUAL_HOST: raw3.io
      LETSENCRYPT_HOST: raw3.io
      LETSENCRYPT_EMAIL: admin@raw3.io
      MONGODB_URI: "${MONGODB_URI}"
      MONGODB_USER: "${MONGODB_USER}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
      PORT: "${PORT}"

  redirect:
    container_name: reverse-proxy
    image: morbz/docker-web-redirect
    restart: always
    environment:
      VIRTUAL_HOST: www.raw3.io,raw3.nl,www.raw3.nl
      LETSENCRYPT_HOST: www.raw3.io,raw3.nl,www.raw3.nl
      LETSENCRYPT_EMAIL: admin@raw3.io
      REDIRECT_TARGET: https://raw3.io

networks:
  default:
    external:
      name: nginx-proxy
